public enum AllEventTypes
{
    EVENT_GAME_SCENE_LOADED,

    EVENT_ENEMY_DIED,
    EVENT_ENEMY_CHANGE_DIRECTION,
    EVENT_ENEMY_MOVE,

    EVENT_USER_LOST,
    EVENT_COMPLETED_WAVE,

    NUM_EVENTS
}